# Generated by Django 2.1.2 on 2019-06-18 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(max_length=7)),
                ('image', models.FileField(default=None, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('item_no', models.CharField(max_length=50, unique=True)),
                ('balance', models.IntegerField()),
                ('cost_per_unit', models.FloatField()),
                ('safety_stock_limit', models.IntegerField()),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminWorkspace.Catagory')),
            ],
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('catagory', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='AdminWorkspace.Catagory')),
            ],
        ),
    ]
