# Generated by Django 2.1.2 on 2019-06-18 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminWorkspace', '0002_remove_vendor_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='catagory',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='AdminWorkspace.Catagory'),
            preserve_default=False,
        ),
    ]
